---
version: '3'
services:
  Bot-trader:
    image: freqtradeorg/freqtrade:stable
    # image: Bot-traderorg/Bot-trader:develop
    # Use plotting image
    # image: Bot-traderorg/Bot-trader:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/Bot-trader/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.Bot-trader.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /Bot-trader/user_data/logs/Bot-trader.log
      --db-url sqlite:////Bot-trader/user_data/tradesv3.sqlite
      --config /Bot-trader/user_data/config.json
      --strategy SampleStrategy
